name: CSharp
on:
  workflow_dispatch:
jobs:
 build:
  runs-on: windows-2019
  env:
    ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  steps:
      - name: Checkout code
        uses: actions/checkout@v2.1.0
        id: checkout_code
      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v1.0.0
        id: setup_msbuild
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: 5.0.x
      - name: Nuget Restore Packages
        run: |
          nuget restore .\SourceUtils.sln
      - name: Try
        run: |
          Get-ChildItem | tree /f || true
      - name: Run MSBuild
        id: run_msbuild
        run: |
          msbuild .\SourceUtils.sln  /t:build /p:Configuration=Debug
      - name: Zip Release
        working-directory: ./SourceUtils/bin/Debug/
        run: powershell Compress-Archive ./ SourceUtils.zip
      - name: Date and time
        id: date
        run: echo "::set-output name=date::$(date +'%H-%M-%d-%m-%Y')"
      - name: Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          release_name: SourceUtils ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
      - name: Upload Zip
        id: upload-zip-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./SourceUtils/bin/Debug/SourceUtils.zip
          asset_name: SourceUtils.zip
          asset_content_type: application/zip
