name: TypeScript
on: workflow_dispatch

jobs:
  build-push:
    runs-on: ubuntu-latest
    name: Builds Typescript
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Building Typescript
        uses: FuLagann/tsc-build-push@v1
        with:
          user-name: "DaLLuZZ"
          user-email: "khrushiov2012@yandex.ru"
          message: "Automatic build"
          directories: SourceUtils.WebExport/Resources

      - name: Trigger ReplayViewRSC Build
        run: |
          curl -XPOST -u "DaLLuZZ:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/DaLLuZZ/ReplayViewRSC/dispatches --data '{"event_type": "AutoBuild"}'
