name: TypeScript
on: workflow_dispatch

jobs:
  build-push:
    runs-on: ubuntu-latest
    name: Builds Typescript
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Building Typescript
        uses: FuLagann/tsc-build-push@v1
        with:
          user-name: "DaLLuZZ"
          user-email: "khrushiov2012@yandex.ru"
          message: "Automatic build"
          directories: SourceUtils.WebExport/Resources

      - name: Purge CDN Cache
        run: |
          curl https://purge.jsdelivr.net/gh/DaLLuZZ/SourceUtils@latest/SourceUtils.WebExport/Resources/js/sourceutils.js
